# Description: This playbook installs Node.js on an EC2 instance using Ansible.
- name: Install Node.js on EC2 instance # Playbook name
  hosts: ec2_instance # Host group name
  gather_facts: no #  Disable gathering facts 
  become: yes # Run tasks as root
  vars: 
    ansible_ssh_private_key_file: /home/runner/.ssh/id_rsa # Path to the private key file
    ansible_python_interpreter: /usr/bin/python3 #  Path to the Python interpreter
    ansible_user: ec2-user # Username to connect to the EC2 instance
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no' # Disable strict host key checking
  tasks:
    - name: Wait for SSH to come up # Wait for SSH to be available
      wait_for: 
        host: "{{ inventory_hostname }}" #  Hostname of the target machine
        port: 22 # SSH port
        delay: 60 # Delay between retries
        timeout: 900
        state: started

    - name: Gathering Facts
      setup:
    - name: Update all packages
      dnf:
        name: '*'
        state: latest
    - name: Install tar and xz for unpacking Node.js binaries
      dnf:
        name:
          - tar
          - xz
        state: present

    - name: Download Node.js binary tarball
      get_url:
        url: https://nodejs.org/dist/v16.14.2/node-v16.14.2-linux-x64.tar.xz
        dest: /tmp/node-v16.14.2-linux-x64.tar.xz

    - name: Extract Node.js binary tarball
      command:
        cmd: tar -xf /tmp/node-v16.14.2-linux-x64.tar.xz -C /usr/local --strip-components 1
    - name: Verify Node.js installation
      command:
        cmd: node -v
      register: node_version

    - name: Display Node.js version
      debug:
        msg: 'Node.js version is {{ node_version.stdout }}'

    - name: Install PM2 globally # Install PM2 globally using
      npm:
        name: pm2 # Package name
        global: yes # Install globally
        state: present # Install the package 